apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsf-deployment
  labels:
    app: jsf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsf-app
  template:
    metadata:
      labels:
        app: jsf-app
    spec:
      containers:
      - name: jsf-app
        image: kaiopiterson/jsf-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: jsf-service
spec:
  selector:
    app: jsf-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
